name: Wheels

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - { os: macos-12, build: macosx_x86_64 }
        - { os: windows-latest, build: win_amd64 }
        - { os: 'ubuntu-20.04', build: manylinux_x86_64 }

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"

    - name: Build wheels
      run: python setup.py bdist_wheel --plat-name=${{ matrix.build }}

    - name: Show build
      run: ls ./dist
