name: Wheels

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        platform: [ macosx_x86_64, macosx_arm64, manylinux_2_17_x86_64, win_amd64 ]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"

    - name: Install build dependencies
      run: pip install build setuptools_scm

    - name: Build wheels
      run: python -m build --wheel --outdir wheelhouse
      env:
        PLAT_NAME: ${{ matrix.platform }}

    - name: Build source distribution
      run: python -m build --sdist --outdir wheelhouse
      if: matrix.platform == 'manylinux_2_17_x86_64'

    - uses: actions/upload-artifact@v3
      with:
        path: ./wheelhouse/*

  show:

    needs: [build]
    runs-on: 'ubuntu-latest'

    steps:

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - name: Show wheels
        run: ls ./dist
