name: Wheels

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          os: [ macos-latest, ubuntu-latest, windows-latest ]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"

    - name: Install build dependencies
      run: pip install build

    - name: Build wheels
      run: python -m build --wheel --outdir wheelhouse

    - uses: actions/upload-artifact@v2
      with:
        path: ./wheelhouse/*.whl

  show:

    needs: [build]
    runs-on: 'ubuntu-20.04'

    steps:

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - name: Show wheels
        run: ls ./dist
