name: Wheels

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        # - { os: macos-12, build: cp38-macosx_x86_64 }
        - { os: windows-latest, build: cp38-win_amd64 }
        - { os: 'ubuntu-20.04', build: cp38-manylinux_x86_64 }

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"

    - name: Install cibuildwheel
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install 'cibuildwheel>=2.11.0'

    - name: Build wheels
      run: python -m cibuildwheel --output-dir wheelhouse

    - name: Show build
      run: ls ./wheelhouse
